version: '3'

services:

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db

  app:
    container_name: app
    image: node:12
    depends_on:
      - mongo
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    tty: true
    restart: unless-stopped
    working_dir: /usr/src/service
    command: npm run start
    ports:
      - 8080:8080
      - 9229:9229
    env_file: .env
    environment:
      - NODE_ENV=development

volumes:
  nodemodules:
    external: true
