version: '2'

services:

  dev:
    image: node:11
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    working_dir: /usr/src/service

  install:
    extends:
      service: dev
    command: npm install

  build:
    extends:
      service: dev
    command: npm run start

volumes:
  nodemodules:
    external: true
